name: zest_trade
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_code_picker: ^3.0.0
  connectivity_plus: ^4.0.2
  http: 0.13.5
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  build_runner: ^2.4.6
  device_info_plus: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
